class CfgServerInfoMenu4
{
   addAction = 0; // Enable/disable action menu item | use 0 to disable | default: 1 (enabled)
   antiHACK = "infiSTAR + BattlEye";
   hostedBy = "ANÔNIMOS";
   ipPort = "Server Altis";
   openKey = "User7"; // https://community.bistudio.com/wiki/inputAction/actions
   openAtLogin = no;
   restart = 6; // Amount of hours before server automatically restarts
   serverName = "MISSÕES";
   class menuItems
   {
      // title AND content accept formatted text ( since update Oct5.2016 )
	  class first
      {
         menuName = "MISSÕES";
         title = "Informações do server <t color='#9370DB'>ANÔNIMOS</t></t><br />";
         content[] = {
            ,
         "__MISSÕES_PRINCIPAIS__<br />",
         "<br />",
         "-COMBOIO SUSPEITO<br />",
         "O jogador devera matar todos os bots do comboio para receber a recompensa de 2 caixa com equipamentos aleatórios<br />",
         "<br />",
         "-ESCOLTA ARMADA<br />", 
         "O jogador devera matar todos os bots da escolta para receber a recompensa de 2 caixa com equipamentos aleatórios<br />",
         "<br />",
         "-OCUPAÇÃO<br />",
         "O jogador devera matar todos os bots da cidade para receber a recompensa de 2 caixa com equipamentos aleatórios<br />",
         "<br />",
         "-POSTO AVANÇADO <br />",
         "O jogador devera matar todos os bots do posto avançado para receber a recompensa de 2 caixa com equipamentos aleatórios<br />",
         "<br />",
         "-PATRULHA DE ALTIS <br />",
         "O jogador devera matar todos os bots da patrulha para receber a recompensa de 2 caixa com equipamentos aleatórios<br />",
         "!!ATENÇÂO!! esta é a unica missão que é possível encontrar os veiculos de artilharia<br />",
         "<br />", 
         "-ACAMPAMENTO DE CAÇADORES <br />",
         "O jogador devera matar todos os bots do acampamento para receber a recompensa de 2 caixa com equipamentos aleatórios<br />",
         "!!ATENÇÂO!! esta é a unica missão que é possível encontrar os silenciadores de 9.3, .338 e miras AMS,LPRS e ghillie suits<br />",
         "<br />", 
         "-GRUPO TERRORISTA<br />",
         "O jogador devera matar todos os bots da cidade para receber a recompensa de 2 caixa com equipamentos minas e explossivos AT,AP<br />",
         "!!ATENÇÂO!! esta é a unica missão que é possível encontrar minas e explossivos AT,AP<br />",
         "<br />", 
         "------------------------------------------------------------------------------------------------------------<br />",
         "__MISSÕES_COLATERAIS__<br />",
         "<br />",
         "-HELICÓPTERO ABATIDO<br />",
         "O jogador devera matar todos os bots para receber a recompensa de 2 caixa com equipamentos aleatórios<br />",
         "<br />", 
         "-PATRULHA DE RECONHECIMENTO<br />", 
         "O jogador devera matar todos os bots da patrulha para receber a recompensa de 2 metralhadoras .50 e 10 energeticos<br />",
         "<br />",
         "-TRAFICANTES<br />",
         "O jogador devera matar todos os bots traficantes para receber a recompensa de 1 caixa e drogas em quantidades aleatorias<br />",
         "<br />", 
         "-ANÁLISE GEOGRÁFICA<br />",
         "O jogador devera encontra um radio escondido para receber a recompensa de 1 caixa de equipamentos aleatorios<br />",
         "<br />",  
         "-CONTRABANDO DE ARMAS<br />", 
         "O jogador devera matar todos os bots para receber a recompensa de 1 caixa com equipamentos aleatórios e 2 veiculos aleatorios<br />",
         "<br />",
         "-CAMINHÃO DE SUPRIMENTO<br />",
         "O jogador devera matar todos os bots para receber a recompensa de 1 caminhâo com equipamentos aleatórios<br />",
         "<br />",
         "-ACAMPAMENTO MILITAR<br />",
         "O jogador devera matar todos os bots para receber a recompensa de 3 caixa com equipamentos aleatórios <br />",
         "!!ATENÇÂO!! esta é a unica missão que é possível encontrar o detector de mina <br />",
         "<br />",  
         "------------------------------------------------------------------------------------------------------------<br />",
         "__MAQUINAS_DE_GUERRA__<br />",
         "<br />",
         "-DRONE ABANDONADO<br />",
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />", 
         "-AERONAVE ABANDONADA<br />",
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />", 
         "-VEÍCULO ANTIAÉREO<br />",
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />", 
         "-VEÍCULO DE COMBATE DE INFANTARIA<br />",
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />", 
         "-VEÍCULO BLINDADO DE COMBATE<br />",
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />", 
         "-TRANSPORTADOR DE TROPA BLINDADO<br />", 
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />",
         "-HELICÓPTERO GUARNECIDO<br />", 
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />",
         "-HELICÓPTERO DE ATAQUE GUARNECIDO<br />", 
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />",
         "-HELICÓPTERO DE SUPORTE<br />", 
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />",
         "-VEÍCULO LEVE DE COMBATE<br />", 
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />",
         "-VIATURAS DE COMBATE<br />",
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />", 
         "-CAVALARIA BLINDADA<br />", 
         "O jogador devera matar todos os bots para receber o veiculo como recompensa<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "__MISSÕES_DE_DINHEIRO__<br />",
         "<br />",
         "-Hackers<br />",
         "O jogador devera matar todos os bots para desbloquear o acesso em uns dod varios laptops, onde ele ira hackear as contas dos jogadoes online, apos ter concluido o jogador ira receber 30.000+0.009 da conta de cada jogador q nao estiver no seu grupo<br />",
         "<br />",
         "-RESGATE AO REFÉM<br />",
         "O jogador devera matar todos os bots para receber a recompensa de $4.500, se caso o jogdor matar o refém a missão acaba<br />",
         "<br />", 
         "-BLOQUEIO NA ESTRADA<br />", 
         "O jogador devera matar todos os bots para receber a recompensa de $4.500<br />",
         "<br />",
         "-ESCOLTA DE DINHEIRO<br />",  
         "O jogador devera matar todos os bots dos veiculos para receber a recompensa de $10.000 ou $15.000 ou $20.000 ou $30.000<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "__MISSÕES_AÉREAS__<br />",
         "<br />",
         "-HELICÓPTERO HOSTIL<br />", 
         "Missão na qual vem (1) helicóptero armado sobrevoando os céus de altis o jogador devera matar todos os bots para, receber 2 caixas com equipamentos aleatórios as caixas se encontrão onde o ultimo bot foi morto e nao onde a ultima aeronave caiu<br />",
         "<br />",
         "-HELICÓPTEROS HOSTIS<br />", 
         "Missão na qual vem (2) helicópteros armados sobrevoando os céus de altis o jogador devera matar todos os bots para, receber 2 caixas com equipamentos aleatórios as caixas se encontrão onde o ultimo bot foi morto e nao onde a ultima aeronave caiu<br />",
         "<br />",
         "-PATRULHA AÉREA<br />", 
         "Missão na qual vem (3) helicópteros armados sobrevoando os céus de altis o jogador devera matar todos os bots para, receber 2 caixas com equipamentos aleatórios as caixas se encontrão onde o ultimo bot foi morto e nao onde a ultima aeronave caiu<br />",
         "<br />",
         "-JATO HOSTIL<br />",
         "Missão na qual vem (1) jato armado sobrevoando os céus de altis o jogador devera matar todos os bots para, receber 2 caixas com equipamentos aleatórios as caixas se encontrão onde o ultimo bot foi morto e nao onde a ultima aeronave caiu<br />", 
         "<br />",
         "-JATOS HOSTIS<br />",
         "Missão na qual vem (2) jatos armados sobrevoando os céus de altis o jogador devera matar todos os bots para, receber 2 caixas com equipamentos aleatórios as caixas se encontrão onde o ultimo bot foi morto e nao onde a ultima aeronave caiu<br />", 
         "<br />",
         "-OPRESSÃO AÉREA<br />",
         "Missão na qual vem (3) jatos armados sobrevoando os céus de altis o jogador devera matar todos os bots para, receber 2 caixas com equipamentos aleatórios as caixas se encontrão onde o ultimo bot foi morto e nao onde a ultima aeronave caiu<br />",
         "<br />",
         "-PATRULHA VTOL<br />",
         "Missão na qual vem (2) VTOL sobrevoando os céus de altis o jogador devera matar todos os bots para, receber 2 caixas com equipamentos aleatórios as caixas se encontrão onde o ultimo bot foi morto e nao onde a ultima aeronave caiu<br />", 
         "------------------------------------------------------------------------------------------------------------<br />",
         "__MISSÕES_AQUÁTICAS__<br />",
         "<br />",
         "Dica compre o submarino<br />",
         "<br />",
         "-EXPEDIÇÃO GRUMEC<br />",
         "O jogador devera matar todos os bots mergulhadores para receber a recompensa de 2 caixa com equipamentos aleatórios<br />",
         "<br />", 
         "-PATRULHA COSTEIRA<br />",
         "Missão na qual vem (2) barcos e (1) helicóptero armado patrulhando a costa altis o jogador devera matar todos os bots para, receber 2 caixas com equipamentos aleatórios as caixas se encontrão onde o ultimo bot foi morto e nao onde a ultimo foi destruido<br />",
         "<br />", 
         "-TESOURO SUBMERSO<br />",
         "O jogador devera matar todos os bots mergulhadores para receber a recompensa de 2 caixa com equipamentos aleatórios e $8.000 <br />",
         "<br />", 
         "-SUPRIMENTOS AFUNDADO<br />",
         "O jogador devera matar todos os bots mergulhadores para receber a recompensa de 4 caixa com equipamentos aleatórios<br />",
         "!!ATENÇÂO!! esta é a unica missão que é possível encontrar as caixas de tamanho grande<br />",
         "<br />", 
         "-BAU DO TESOURO<br />",
         "O jogador devera matar todos os bots mergulhadores para receber a recompensa de $50.000<br />",
         "<br />", 
         "------------------------------------------------------------------------------------------------------------<br />",
			"PRESSIONE ESC PARA SAIR"
         }; 
      };
   };
};