class Cfgserverinfomenu7
{
   addAction = 0; // Enable/disable action menu item | use 0 to disable | default: 1 (enabled)
   antiHACK = "infiSTAR + BattlEye";
   hostedBy = "ANÔNIMOS";
   ipPort = "Server Altis";
   openKey = "User7"; // https://community.bistudio.com/wiki/inputAction/actions
   openAtLogin = no;
   restart = 6; // Amount of hours before server automatically restarts
   serverName = "SISTEMA DE GUINCHO DOS HELICOPTEROS";
   class menuItems
   {
      // title AND content accept formatted text ( since update Oct5.2016 )
	  class first
      {
         menuName = ".";
         title = "SISTEMA DE GUINCHO DOS HELICOPTEROS <t color='#9370DB'>ANÔNIMOS</t></t><br />";
         content[] = {
----------  ,
         "Slingloading é um recurso que foi adicionado no ArmA 3 com o lançamento do Helicopters DLC.<br />",
         "Ele permite que a maioria dos helicópteros de asa rotativa transportam veículos e cargas por meio de cordas presas à parte inferior da fuselagem.<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "Fundamentos<br />",
         "<br />",
         "A maioria dos helicópteros no ArmA 3 é capaz de carregar cargas embaixo deles.<br />",
         "<br />",
         "Isso é feito prendendo cordas ao objeto (o processo é automático) enquanto pairando em uma altitude segura recomendada entre 30-40 metros acima do alvo e, em seguida, baixando o gancho.<br />",
         "<br />",
         "Para obter mais precisão durante o processo de enganchar ou desprender, um assistente de camera pode ser alternado para ser exibido no HUD do jogador. O assistente mostra uma representação circular 2D da posição da aeronave e alertará o piloto se ele pairar muito longe ou muito alto do alvo.<br />",
         "<br />",
         "A maioria dos helicópteros, como o CH-67 Huron ou o CH-49 Mohawk, também possuem terminais integrados à cabine da aeronave e podem ser vistos em primeira pessoa.<br />",
         "<br />",
         "Eles fornecem imagens diretas da parte inferior da aeronave; desde que o reprodutor possua Picture-in-Picture (PIP) habilitado em suas configurações gráficas.<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "Limitações<br />",
         "<br />",
         "Uma vez preso, o peso extra da carga irá sobrecarregar a velocidade e o manuseio do helicóptero.<br />",
         "<br />",
         "Movimento súbito ou pairar muito longe / muito alto da carga interromperá o processo de enganchamento.<br />",
         "<br />",
         "Se o helicóptero voar para muito longe, o gancho também se retrairá automaticamente e a tentativa de carregamento será cancelada.<br />",
         "<br />",
         "As cordas de levantamento não são indestrutíveis e podem ser danificadas caso se quebrem devido à colisão com objetos rígidos, como cabos de força, ou sejam alvejadas por armas de fogo.<br />",
         "<br />",
         "Além disso, nem todos os veículos podem ser carregados com estilingue.<br />",
         "<br />",
         "Os tanques de batalha principais, como o M2A1 Slammer ou o T-100 Varsuk, por exemplo, não podem ser levantados simplesmente porque excedem em muito o peso máximo de levantamento de todos os helicópteros. Da mesma forma, muitos IFVs e APCs, como o AMV-7 Marshall , MSE-3 Marid ou qualquer um dos caminhões maiores, não podem ser carregados porque são muito grandes ou também muito pesados.<br />",
         "<br />",
         "Por outro lado, embora nenhum helicóptero do jogo seja obviamente capaz de carregar outros helicópteros, certas aeronaves de asa fixa como o A-143 Buzzard são compactas e leves o suficiente para serem transportadas por helicópteros de carga pesada específicos , como o CSAT Mi-290 Taru.<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "Helicópteros suportados<br />",
         "<br />",
         "OBSERVE<br />",
         "-Todos os valores de massa são referidos em quilogramas e não em toneladas por razões de consistência.<br />",
         "-Os valores de peso decimais são arredondados e ignorados por uma questão de simplicidade.<br />",
         "-Recipientes e cápsulas para o OTAN CH-67 Huron e CSAT Mi-290 Taru não estão listados em suas tabelas, pois essas caixas são projetadas especificamente para serem carregadas apenas por seus respectivos helicópteros.<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "M900<br />",
         "Capacidade máxima de peso de carga: 500 kg<br />",
         "Uma versão civil de suas contrapartes militares,<br />",
         "o M900 tem as mesmas restrições de peso de ambos e tem um limite máximo de carga de 500 kg.<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "Hummingbird MH-9<br />",
         "Capacidade máxima de peso de carga: 500 kg<br />",
         "O Hummingbird tem as mesmas restrições de peso do Pawnee / M900 e é igualmente incapaz de transportar veículos de médio ou grande porte.<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "AH-9 Pawnee<br />",
         "Capacidade máxima de peso de carga: 500 kg<br />",
         "Devido ao pequeno tamanho de sua fuselagem, o Pawnee não pode transportar veículos de médio ou grande porte e só pode levantar cargas que pesem até 500 kg. Isso se restringe principalmente ao levantamento de Quadbikes e pequenas caixas de munição apenas.<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "PO-30 Orca<br />",
         "Capacidade máxima de peso de carga: 2.000 kg<br />",
         "Um helicóptero utilitário leve usado pelas forças do Mediterrâneo CSAT. Ele pode transportar mais do que a família de helicópteros NATO xH-9, mas é incapaz de levantar os mesmos tipos de cargas disponíveis para o Ghost Hawk e o Mohawk.Uma vez que o motor do PO-30 não é tão potente quanto o Hellcat da AAF, seu manuseio sofre uma grande penalidade ao levantar veículos que estão próximos do seu limite de tolerância de peso (ou seja, o MB 4WD ).<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "WY-55 Hellcat<br />",
         "Capacidade máxima de peso de carga: 2.000 kg.<br />",
         "Outro helicóptero utilitário leve usado pela AAF que é aproximadamente equivalente ao CSAT PO-30. Possui as mesmas restrições de objetos que o PO-30, mas manuseia um pouco melhor ao lançar um objeto devido aos seus motores serem mais poderosos.<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "UH-80 Ghost Hawk<br />",
         "Capacidade máxima de peso de carga: 4000 kg<br />",
         "O segundo dos dois helicópteros utilitários de levantamento médio, exceto o Mohawk da AAF , o Ghost Hawk pode carregar caixas pesadas e veículos leves.<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "CH-49 Mohawk<br />",
         "Capacidade máxima de peso de carga: 5000 kg<br />",
         "Um dos dois helicópteros utilitários de médio levantamento, o Mohawk é capaz de transportar objetos ligeiramente mais pesados ​​do que o Ghost Hawk da OTAN, uma vez que pode tolerar 1.000 kg adicionais de carga, mas está restrito ao mesmo tipos de veículos.<br />",
         "Deve-se notar que o Mohawk sofre muito com a penalidade de velocidade e manuseio ao carregar objetos significativamente pesados ​​que estão perto de seu limite de peso; bons exemplos são o Van Transport e o UGV Stomper por exemplo.<br />",
         "NOTA: O Mohawk não pode transportar a variante Cargo do Van , apesar de pesar exatamente 5.000 kg. No entanto, é capaz de transportar as outras três variantes (Ambulância / Serviços / Transporte), apesar das duas anteriores estarem bem acima do seu limite de peso máximo em 15 kg.<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "CH-67 Huron<br />",
         "Capacidade máxima de peso de carga: 12.000 kg<br />",
         "Um helicóptero de transporte pesado, o Huron pode carregar cargas significativamente mais pesadas do que a maioria dos helicópteros, exceto o CSAT Mi-290. Ele tem uma variedade de contêineres de suporte que são projetados especificamente para serem içados pelo Huron, variando de uma cisterna de combustível, suprimento de munição, estação médica de campo e contêineres de reparo de veículos.<br />",
         "É um dos únicos dois helicópteros heavy-lift que são suficientemente poderosa para transportar tanto o A-143 Buzzard e as Para-199 Neophron jatos de asa fixa.<br />",
         "O Huron é capaz de transportar o transportador apenas variantes do HEMTT , e também é capaz de transportar as configurações mais leves do caminhão Zamak (ele não pode transportar as variantes mais pesadas de munição / reparo).<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "Mi-290 Taru<br />",
         "Capacidade máxima de peso de carga: 13.500 kg<br />",
         "O mais forte dos dois helicópteros de carga pesada e de todos os helicópteros com capacidade de carga de estilingue, o Mi-290 serve como equivalente do CSAT ao Huron da OTAN. Como é o caso do Huron, o Mi-290 também possui uma variedade de pods carregáveis ​​com funda que são projetados especificamente com sua estrutura em mente. Eles variam de bancadas abertas a vários contêineres de suporte.<br />",
         "Ao contrário do Huron, no entanto, o Mi-290 pode levantar 1.500 kgs adicionais de carga e também é notável por ser o único helicóptero que pode transportar o HEMTT e todas as variantes da família de caminhões utilitários Zamak (embora ainda seja incapaz de carregue as variantes mais pesadas do HEMTT ou do Zamak Fuel).<br />",
         "Também deve ser notado que as variantes do Mi-290 que já têm contêineres afixados no centro da fuselagem não podem carregar qualquer carga.<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "SERA ARRUMADO A LISTA<br />",
         "<br />",
         "Nome do Objeto---------------------------Massa <br />",
         "Kart------------------------------------------150<br />",
         "Quadricíclo------------------------------280<br />",
         "Barco de assalto / barco de resgate------565<br />",
         "Hatchback (todas as variantes)-----------1090<br />",
         "SUV--------------------------------------1600<br />",
         "Offroad (HMG)----------------------------1739<br />",
         "Offroad (AT)-----------------------------1764<br />",
         "Offroad/Offroad(Reparação)/(Serviços)----1835<br />",
         "MB 4WD (AT)------------------------------1841<br />",
         "MB 4WD-----------------------------------1862<br />",
         "Caminhão---------------------------------2400<br />",
         "Truck Boxer------------------------------2509<br />",
         "SDV--------------------------------------2600<br />",
         "MQ4A Greyhawk / K40 Ababil---------------3000<br />",
         "Truck Fuel-------------------------------3200<br />",
         "Prowler (todas as variantes)-------------3413<br />",
         "Qilin (AT)-------------------------------3907<br />",
         "Qilin (todas as variantes exceto AT)-----3924<br />",
         "MB 4WD (LMG)-----------------------------3997<br />",
         "UGV Stomper/UGV Saif(todas as variantes)-4266<br />",
         "AWC Nyx 303 (Recon)----------------------4820<br />",
         "AWC Nyx 301 (AT) / 304 (Autocanhão)------4820<br />",
         "AWC Nyx 302 (AA)-------------------------4950<br />",
         "Van (carga)/(serviços)-------------------4950<br />",
         "RHIB-------------------------------------5001<br />",
         "Transporte de Van / Van (Ambulância)-----5015<br />",
         "A-143 Buzzard----------------------------6700<br />",
         "Hunter-----------------------------------8306<br />",
         "Armed Hunters (HMG/GMG)------------------8389<br />",
         "Ifrit------------------------------------8392<br />",
         "Armed Ifrits (HMG/GMG)-------------------8439<br />",
         "Speedboat Minigun------------------------9016<br />",
         "Speedboat HMG----------------------------9016<br />",
         "Strider (all variants)-------------------9700<br />",
         "Zamak Transport--------------------------10800<br />",
         "HEMTT Transport--------------------------10942<br />",
         "To-199 Neophron--------------------------11000<br />",
         "Zamak Transport (Covered)----------------11000<br />",
         "HEMTT Transport (Covered)----------------11026<br />",
         "Zamak Medical----------------------------11500<br />",
         "Zamak Ammo/Repair------------------------11500<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
         "<br />",
         "informações retiradas -> <t color='#0091CD'><a href='https://armedassault.fandom.com/wiki/Slingloading'>LINK</a></t><br /><br />",
         "DICA: as aeronave VTOL e Y-32 Xian tem uma classe para transportar veículos<br />",
         "<br />",
         "------------------------------------------------------------------------------------------------------------<br />",
			"PRESSIONE ESC PARA SAIR"
         }; 
      };
   };
};